### ISSUE TITLE
Allow path based routing and setting path type for ingress resource.

### ISSUE THREAD

**Issue by Forbzy** [atlassian/data-center-helm-charts#247]
**Describe the bug**
Can't connect to application when using path based routing. Unable to set path type for ingress resource. It has a fixed value of Prefix. Can we update the chart so this value can be provided by the developer. At the moment I can't seem to connect to my jira application from the browser.

**Existing Behaviour**
I'm interested in doing path based routing with jira and confluence. At the moment I'm not able to connect to application using the ingress resource host path. https://my-host.com/jira

**Steps to Reproduce**
1. Deploy Jira with ingress resource

**Expected Behaviour**
Connect to application using the ingress resource host path.

Below is what my ingress resource looks like.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: jira
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  name: jira
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - my-host.com
    secretName: my-host.com
  rules:
  - host: my-host.com
    http:
      paths:
      - backend:
          serviceName: jira
          servicePort: 80
        path: /jira
        pathType: Prefix
```
