### ISSUE TITLE
[Bug] - Unable to control some StatefulSet configurations with values.yaml

### ISSUE THREAD

**Issue by Wicaeed** [atlassian/data-center-helm-charts#406]
### Bug

Hello, I am trying to activate clustering via the Helm chart and my values.yaml file, but not having any luck. It seems like the clustering value (and others, see below), do not result in the proper values being set in the StatefulSet object:

My (partial) values.yaml:
```
cert:
  environment: dev
  secret-name: dev-certs

jira:
  clustering:
    enabled: true
  replicaCount: 1
  setPermissions: false
  securityContext: {}
  containerSecurityContext: {}
  image:
    repository: registry01.my.corp/sre/jira-software 
    pullPolicy: IfNotPresent
    tag: ""
<...snip...>
```

Chart.yaml (since we are using atlassian/data-center-helm-charts as a dependent Chart):
```
apiVersion: v2
name: sd-jira
description: A chart for installing Jira on K8s
type: application
version: 0.1.1
dependencies:
  - name: cert
    version: "1.1.0"
    repository: "http://chartmuseum.my.corp/"  
  - name: jira
    version: ~1.3.0
    repository: https://atlassian.github.io/data-center-helm-charts/
```

When I look at the output of Helm Template, I do not see the clustering value set on the StatefulSet. Also notice the value of `SET_PERMISSIONS` from values.yaml above is also not honored:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sd-jira
  labels:
    helm.sh/chart: jira-1.3.0
    app.kubernetes.io/name: jira
    app.kubernetes.io/instance: sd-jira
    app.kubernetes.io/version: "8.20.7"
    app.kubernetes.io/managed-by: Helm
    
spec:
  replicas: 1
  serviceName: sd-jira
  selector:
    matchLabels:
      app.kubernetes.io/name: jira
      app.kubernetes.io/instance: sd-jira
  template:
    metadata:
      annotations:
        checksum/config-jvm: 223f26e47250d997193c133d041f8b49427c3a68177aadc5861025f97dcc4d50
        
      labels:
        app.kubernetes.io/name: jira
        app.kubernetes.io/instance: sd-jira
        
    spec:
      serviceAccountName: svc-sd-jira
      terminationGracePeriodSeconds: 30
      securityContext:
        
        
        fsGroup: 2001
      initContainers:
        
      containers:
        - name: jira
          image: "registry01.my.corp/sre/jira-software:8.20.7"
          imagePullPolicy: IfNotPresent
          env:
            
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            
            
            
            - name: ATL_PROXY_NAME
              value: "jira.my.corp.dev"
            - name: ATL_PROXY_PORT
              value: "443"
            
            
            - name: ATL_DB_TYPE
              value: "mysql57"
            
            
            - name: ATL_DB_DRIVER
              value: "com.mysql.jdbc.Driver"
            
            
            - name: ATL_JDBC_URL
              value: "jdbc:mysql://address=(protocol=tcp)(host=jira-db)(port=3306)/jirak8s?sessionVariables=default_storage_engine=InnoDB"
            
            
            - name: ATL_JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: jira-db-secret
                  key: USERNAME
            - name: ATL_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-db-secret
                  key: PASSWORD
            
            
            
            
            - name: SET_PERMISSIONS
              value: "true"
            - name: JIRA_SHARED_HOME
              value: "/var/atlassian/application-data/shared-home"
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: sd-jira-jvm-config
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: sd-jira-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: sd-jira-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: sd-jira-jvm-config
            
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: ehcache
              containerPort: 40001 
              protocol: TCP 
            - name: ehcacheobject
              containerPort: 40011
              protocol: TCP
            
          readinessProbe:
            httpGet:
              port: 8080
              path: /status
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          resources:
            requests:
              cpu: "2"
              memory: 2G
          volumeMounts:
            
            - name: local-home
              mountPath: "/var/atlassian/application-data/jira"
            - name: local-home
              mountPath: "/opt/atlassian/jira/logs"
              subPath: "log"
            - name: shared-home
              mountPath: "/var/atlassian/application-data/shared-home"
            
            
            
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "/shutdown-wait.sh"]
        
        
        
      volumes:
        
        
        - name: shared-home
          persistentVolumeClaim:
            claimName: jira-shared-home
        
        
        
        
        
  
  
  volumeClaimTemplates:
  - metadata:
      name: local-home
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "portworx-pso-fb-v3"
      resources:
        requests:
          storage: 8Gi
```

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@Wicaeed so your pedendency chart is called jira. I guess you are missing another `jira` from values.yaml https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/jira/values.yaml#L375 - clustering is a child of jira. Can you please give it a try this way?

```
jira:
  jira:
    clustering:
      enabled: true
```
