### ISSUE TITLE
[Suggestion] - Allow smtp configuration via secret / chart

### ISSUE THREAD

**Issue by NandoTheessen** [atlassian/data-center-helm-charts#437]
### Suggestion

It isn't possible to configure SMTP credentials via the helm chart.
Again, this requires manual interaction and secret knowledge, which we'd like to avoid.

Again, happy to provide a PR if given a pointer on how to provide these credentials to Jira.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
Hi @NandoTheessen  while this is not supported out of the box (i.e. a dedicated secret for smtp) I think it should be possible to pass smtp props in setenv.sh and mount the entire file from a pre-created secret. In your values.yaml:

```
additionalFiles:
  - name: custom-config
    type: configMap
    key: setenv.sh
    mountPath:  /opt/atlassian/jira/bin
```

This way, you can pre-create the secret (or ConfigMap) with mailserver props in CATALINA_OPTS or JAVA_OPTS and it'll get mounted to the container. In theory it should do the trick (I haven't yet verified it)
