### ISSUE TITLE
[Suggestion] - Should Bitbucket Smart Mirror have a livenessProbe?

### ISSUE THREAD

**Issue by JSRAF** [atlassian/data-center-helm-charts#438]
### Suggestion

I was wondering why the Helm chart does not have a option for setting up a livenessProbe for the Bitbucket Smart Mirror. There is a open port for the readinessProbe already there. Is there no need for a livenessProbe or should this be added in the future?

My other concern is about the Security Context of the Smart Mirror since it runs as the root [user](https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/bitbucket/templates/statefulset.yaml#L56) for the ability to change the volume permissions. Also you can't change the allowPrivilegeEscalation value either on the Values file unfortunately. I think this should be configured more securely if possible.

### Product

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjeongatl** [comment]
Hi @JSRAF thanks for suggestion. Could you elaborate more on your suggestions. It would help us prioritising this if you could provide good use cases(PRs, examples etc...).

**Comment by bianchi2** [comment]
Liveness probe has already made it to Jira. We're planning to add them to all charts.

As to the securityContext, it should be fully configurable.

**Comment by JSRAF** [comment]
So the initContainer is supposed to run as root and the main container would work if I applied the following securityContext settings to it?
```
securityContext:
  runAsUser: 2003
  runAsGroup: 2003
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
```
