### ISSUE TITLE
[Suggestion] - jira chart values.yaml is missing schema option for Postgres

### ISSUE THREAD

**Issue by mumbley** [atlassian/data-center-helm-charts#457]
### Suggestion

The helm chart includes the following configurable items for the database
```
database:
  type:
  url:
  driver:
  credentials:
    secretName:
    usernameSecretKey:
    passwordSecretKey:
```
Which, is _nearly_ everything needed to populate the `dbconfig.xml` file, but, for Postgres it is missing the `schema` (see below block) and, possibly, because of this, the DB config has to be re-configured on first install (and install of subsequent cluster pods (see https://github.com/atlassian/data-center-helm-charts/issues/456)

```
<jira-database-config>
  <name>defaultDS</name>
  <delegator-name>default</delegator-name>
  <database-type>postgresaurora96</database-type>
  <schema-name>public</schema-name>
```

Adding `schema` as an option for Postgres would resolve this issue (and, if this is an option, it's not in the chart values.yaml)

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
