### ISSUE TITLE
[Suggestion] - Support single-node Confluence deployments

### ISSUE THREAD

**Issue by konrad-garus** [atlassian/data-center-helm-charts#459]
### Suggestion

It would be nice if the Confluence chart supported single-node deployments. You don't always need the hassle and additional costs of additional volumes, processes (Synchrony) etc.

1. Make "shared home" optional. When it's disabled, don't create the shared home volume, its corresponding volume mount, or the `ATL_PRODUCT_HOME_SHARED` env var.
2. Support using in-process Synchrony. We don't need the extra pod with its own heap etc. Let us just have a service that points to 8091 on Confluence.

### Product

Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by konrad-garus** [comment]
Why not get rid of shared home? Confluence is perfectly happy without it, as long as it's a single-node deployment. Which is what I'm asking for here.

In fact, we've recently talked about it for Bitbucket: https://github.com/atlassian/data-center-helm-charts/issues/379.

Right now I'm using Kustomize for it and it works just fine. What I'm suggesting here is to make it a part of the official chart, to support single-node deployments.

My Kustomize patches look like this:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluence
spec:
  template:
    spec:
      containers:
        - name: confluence
          env:
          - $patch: delete
            name: ATL_PRODUCT_HOME_SHARED
          volumeMounts:
          - $patch: replace
          - name: local-home
            mountPath: /var/atlassian/application-data/confluence
      volumes:
      - $patch: delete
```

```
# By replacing additional_jvm_args, this update does two things:
# 
# 1. It removes the config params that configure standalone Synchrony
# 2. It tweaks Confluence configuration to have better behavior around job purge (causing excessive DB load)
#
# The default args (as of 1.5.1) are:
# -Dconfluence.cluster.hazelcast.listenPort=5701
# -Dsynchrony.btf.disabled=true
# -Dsynchrony.by.default.enable.collab.editing.if.manually.managed=true
# -Dconfluence.clusterNodeName.useHostname=true
# -Datlassian.logging.cloud.enabled=false
# -XX:ActiveProcessorCount=1
apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-jvm-config
data:
  additional_jvm_args: -Djobs.limit.per.purge=50000 -Dall.jobs.ttl.hours=168
```

```
apiVersion: v1
kind: Service
metadata:
  name: confluence
spec:
  ports:
  - name: synchrony
    port: 8091
    targetPort: 8091
    protocol: TCP
```
