### ISSUE TITLE
[Suggestion] - add support for annotations on Grafana dashboard ConfigMap

### ISSUE THREAD

**Issue by sleterrier** [atlassian/data-center-helm-charts#633]
### Suggestion

Hi,

Thanks for maintaining Grafana dashboards as part of the charts, it is a great added value!

It would however be very convenient if one could add `annotations` to the Grafana dashboard's `ConfigMaps`, so the dashboards can be stored under a folder structure within Grafana.

```yaml
apiVersion: v1
kind: ConfigMap

data:
  example-dashboard.json: |-
    {
      ...
    }
metadata:
  annotations:
    k8s-sidecar-target-directory: /tmp/dashboards/example-folder
  labels:
    grafana_dashboard: example-tag
  name: example-name
  namespace: example-namespace
```

### Product

Jira, Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
