### ISSUE TITLE
[Suggestion] - Switching to clustered deployment on Confluence 

### ISSUE THREAD

**Issue by amhibyan** [atlassian/data-center-helm-charts#642]
### Suggestion

Hello,

I was recently testing out a clustered deployment on Confluence Data Center via the helm chart and was following some steps from [Issue #555 ](https://github.com/atlassian/data-center-helm-charts/issues/555) regarding emptying the PVCs and remove the confluence.cfg.xml

Is it possible to switch to a clustered deployment without having to remove the cfg.xml and emptying the PVCs on a deployment that is already being used in production?

### Product

Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
Hi @amhibyan yes, it is possible. You need to add (in addition to clustering.enabled):

```
confluence:
  additionalEnvironmentVariables:
    - name: ATL_FORCE_CFG_UPDATE
      value: "true"
```
This env will be passed to entrypoint script which will update the clustering property.
