### ISSUE TITLE
[Breaking - Changes] - podAnnotations don't support Datadog labels anymore 

### ISSUE THREAD

**Issue by suleyman-ableto** [atlassian/data-center-helm-charts#681]
### Suggestion

We are having issue to pass Datadog autodiscovery annotations with the new pod Annotation changes.

````yaml
podAnnotations:
  ad.datadoghq.com/jira.check_names: '["jira"]'
  ad.datadoghq.com/jira.init_configs: '[{"is_jmx": true, "collect_default_metrics":true}]'
  ad.datadoghq.com/jira.instances: '[{"host": "%%host%%","port":"9091"}]'
  ad.datadoghq.com/jira.logs: '[{"source":"jira","service":"jira"}]'
````

Error Message
`Error: UPGRADE FAILED: YAML parse error on jira/templates/tests/test-application-status.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .metadata.annotations of type string`

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
