### ISSUE TITLE
[Suggestion] - [jira] Use special variable to right separate mount for logs and home

### ISSUE THREAD

**Issue by w1ndblow** [atlassian/data-center-helm-charts#844]
### Suggestion

problem happen with config

```yaml
localHome:
    persistentVolumeClaim:
      create: true
```

Into the pod mounts other volume

```bash
$ df
/dev/sdg   <> <> <>   1% /opt/atlassian/jira/logs
```

when pvc is creating it binds to first local-home mount (/opt/atlassian/jira/logs) and logs get space whereas local-home directory /opt/atlassian/jira/ is not, it can see `df` command 

if my decision https://github.com/atlassian/data-center-helm-charts/pull/842 is not satisfied with our plan, i suggest create other variable and pvc for that

```yaml
logs:
    persistentVolumeClaim:
      create: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
