### ISSUE TITLE
[Suggestion] - Ingress : support multiple path

### ISSUE THREAD

**Issue by j0nathan33** [atlassian/data-center-helm-charts#920]
### Suggestion

For my jira instance, I will need to support multiple paths in ingress because I need to redirect some path to another sevice. This service handle some custom Jira images. Can you support this feature ?

Thank

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j0nathan33** [comment]
Context : Where at work, we have almost bigger number of jira server instance in world. In few month, we target to have 3 jiradc instance and all jira server will be archived but available if anyone need it. 

If we have to upload data on each pvc, it will be very complicated and too many errors can occurs (Somebody forgot to modify script when he created new test instance, pvc name/id has changed, etc). 
 
My ideal ingress should look like this : 
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jira701
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - jira701.u******.org
      secretName: keyvault-jira701
  rules:
    - host: jira701.u******.org
      http:
        paths:
          - path: /jira
            pathType: Prefix
            backend:
              service:
                name: jira701
                port:
                  number: 80
          - path: /jira/uimages
            pathType: Prefix
            backend:
              service:
                name: jira-static-content
                port:
                  number: 80
```

Main benefit from ingress.additionalPaths:
1) It is easier to maintain on all Jira instances
2) We can't create a new docker image every time, because when we redeploy the node, almost each time, advances roadmap isn't enabled.
3) less downtime for add/remove static content (Some jiradc instance, we have some difference domain name by node and some node isn't HA. This node is only accessible from the Internet and it have some custom firewall rule. Security teams request it)
4) For external node, user has only access to this node. If we point image url to another server directly, user will not see image because external user don't have full access to internal network.
